import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        FormData: 'readonly',
        logger: 'readonly',
        navigator: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        Image: 'readonly',
        alert: 'readonly',
      },
    },
    files: ['src/js/**/*.js'],
    rules: {
      'indent': ['error', 2],
      'quotes': ['error', 'double'],
      'semi': ['error', 'always'],
      'no-unused-vars': ['warn'],
      'no-console': ['warn'],
      'prefer-const': ['error'],
      'no-var': ['error'],
      'eqeqeq': ['error', 'always'],
      'curly': ['error', 'all'],
      'brace-style': ['error', '1tbs'],
      'comma-dangle': ['error', 'always-multiline'],
      'object-curly-spacing': ['error', 'always'],
      'array-bracket-spacing': ['error', 'never'],
      'space-before-function-paren': ['error', 'never'],
      'keyword-spacing': ['error', { 'before': true, 'after': true }],
      'space-infix-ops': ['error'],
      'space-unary-ops': ['error', { 'words': true, 'nonwords': false }],
      'no-trailing-spaces': ['error'],
      'eol-last': ['error', 'always'],
      'no-multiple-empty-lines': ['error', { 'max': 2 }],
      'max-len': ['warn', { 'code': 100, 'ignoreUrls': true }],
    },
  },
];